version: '3'
services:
  ipfs:
    build:
      context: .
      dockerfile: "ipfsbuild_${ARCH}"
    ports: 
      - '5001:5001'
      - '4001:4001'
      - '4002:4002/udp'
      - '8081:8081'
    volumes:
    - ipfs-data:/data/ipfs
  rabbit:
    image: rabbitmq:alpine
  couchdb:
    image: ${COUCHDB}
    ports:
    - "5984:5984"
    environment:
    - COUCHDB_USER=${COUCH_USER}
    - COUCHDB_PASSWORD=${COUCH_PASSWORD}
    volumes:
      - couchdb-data:/opt/couchdb/data
      - ./config/couchdb.ini:/opt/couchdb/etc/local.ini
  worker:
    build: .
    command: celery -A sananode worker --loglevel=info
    volumes:
      - .:/code/
    depends_on:
      - rabbit
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - 8000:8000
volumes:
  couchdb-data:
  ipfs-data: