version: '3'

services:
  ipfs:
    image: jbenet/go-ipfs
  rabbit:
    image: rabbitmq:alpine
  redis:
    image: redis
  db:
    image: postgres
  couchdb:
    image: couchdb
    ports:
    - "8001:5984"
  worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/code/
    depends_on:
      - rabbit
      - redis
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - 8000:8000
    depends_on:
      - worker
      - db