version: '3'

services:
  ipfs:
    image: jbenet/go-ipfs
  web:
    build: .
      command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    #depends_on:
    #  - ipfs