version: '3'

services:
  ipfs:
    build:
      context: .
      dockerfile: ipfsbuild
    ports:
    - "5001:5001"
    volumes:
    - ipfs-data:/data/ipfs
  rabbit:
    image: rabbitmq:alpine
  couchdb:
    image: matthiasg/rpi-couchdb
    ports:
    - "5984:5984"
    environment:
    - COUCHDB_USER=admin 
    - COUCHDB_PASSWORD=admin
    volumes:
      - couchdb-data:/opt/couchdb/data
      - ./config/couchdb.ini:/opt/couchdb/etc/local.ini
  worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/code/
    depends_on:
      - rabbit
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - 8000:8000
volumes:
  couchdb-data:
  ipfs-data: