version: '3'

services:
  ipfs:
    image: jbenet/go-ipfs
  web:
    build: .
    command: python manage.py test
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    #depends_on:
    #  - ipfs